<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWZn5Kct\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWZn5Kct/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerWZn5Kct.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerWZn5Kct\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerWZn5Kct\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'WZn5Kct',
    'container.build_id' => '55e465f1',
    'container.build_time' => 1544019657,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerWZn5Kct');
