<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVo3VSGV\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVo3VSGV/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerVo3VSGV.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerVo3VSGV\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerVo3VSGV\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Vo3VSGV',
    'container.build_id' => '8a7e11c5',
    'container.build_time' => 1541497834,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerVo3VSGV');
