<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOo7piwG\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOo7piwG/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerOo7piwG.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerOo7piwG\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerOo7piwG\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Oo7piwG',
    'container.build_id' => 'b006b1c8',
    'container.build_time' => 1543420205,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerOo7piwG');
